### ISSUE TITLE
[Suggestion] When a player is in your circle, the player should have a little red tint to indicate that you can hit the player

### ISSUE THREAD

**Issue by SalmonSnakeD** [uku3lig/hitrange#4]
So when a player is in your circle, the player's skin should have a colored tint to it, this would indicate that the player is in your reach and you can hit it. 

When a player is in your reach, the player's own circle will turn green as of now. But I personally don't like that I see tens of circles in a small area and it would be better to only show my circle and only show other player's circles if I've enabled in a config file, and also highlight the player when in my range.

The red tint strength and maybe color even could be configured from a config file, or you could add a Modmenu intregation.
I also love this idea #3, please implement these if you have time and motivation of course 😊🙏

**Comment by uku3lig** [comment]
> it would be better to only show my circle and only show other player's circles if I've enabled in a config file

that's... already a feature? go in the mod settings and see if you can find what pleases you

> when a player is in your circle, the player's skin should have a colored tint to it

while i can understand your wish for such a feature, i feel like it just doesn't fit the purpose of the mod; additionally, it would contribute even more to the mod feeling "cheaty" which is not something i necessarily like

> or you could add a Modmenu intregation

again, there already is
